--- SCD 

INSERT INTO	ACTORS_HISTORY_SCD
	WITH STREAK_STARTED AS (
			SELECT
				ACTORID,
				ACTOR,
				QUALITY_CLASS,
				IS_ACTIVE,
				YEAR,
				LAG(QUALITY_CLASS, 1) OVER ( PARTITION BY ACTORID ORDER BY YEAR) <> QUALITY_CLASS
				OR LAG(QUALITY_CLASS, 1) OVER (PARTITION BY ACTORID ORDER BY YEAR) IS NULL
				OR LAG(IS_ACTIVE, 1) OVER (	PARTITION BY ACTORID ORDER BY YEAR) <> IS_ACTIVE
				OR LAG(IS_ACTIVE, 1) OVER (	PARTITION BY ACTORID ORDER BY YEAR) IS NULL AS DID_CHANGE
			FROM
				ACTORS
			WHERE YEAR<2021
		),
		STREAK_IDENTIFIED AS (
			SELECT
				ACTORID,
				ACTOR,
				QUALITY_CLASS,
				IS_ACTIVE,
				YEAR,
				SUM(CASE
						WHEN DID_CHANGE THEN 1
						ELSE 0
					END
				) OVER (PARTITION BY ACTORID	ORDER BY	YEAR) AS STREAK_IDENTIFIER
			FROM
				STREAK_STARTED
		),
		AGGREGATED AS (
			SELECT
				ACTORID,
				ACTOR,
				QUALITY_CLASS,
				IS_ACTIVE,
				STREAK_IDENTIFIER,
				MIN(YEAR) AS START_DATE,
				MAX(YEAR) AS END_DATE
			FROM
				STREAK_IDENTIFIED
			GROUP BY
				ACTORID,ACTOR,QUALITY_CLASS,IS_ACTIVE,STREAK_IDENTIFIER
		)
		
	SELECT
		ACTORID,
		ACTOR,
		QUALITY_CLASS,
		IS_ACTIVE,
		START_DATE,
		END_DATE,
		2020 as CURRENT_YEAR
	FROM
		AGGREGATED
	ORDER BY
		ACTOR,
		START_DATE;